In [57]:
import numpy as np

In [58]:
## Prerequisiste

### Prerequisites
1. Linear function
2. Gradient calculation
3. Parameters update

In [59]:
data = [(1, 2), (3, 4), (5, 9), (2, 3)]
data = np.array(data)
data

array([[1, 2],
       [3, 4],
       [5, 9],
       [2, 3]])

In [60]:
data[:, 0]

array([1, 3, 5, 2])

In [ ]:
arr1 = np.array((2, 3, 4, 5))
arr2 = np.array((1, 1, 1, 1))

arr3 = (arr1 - arr2)**2
arr3

array([ 1,  4,  9, 16])

In [73]:
rg = np.random.default_rng()

rg.random((3,))


array([0.08599377, 0.11784141, 0.43285078])

In [ ]:

class LinearRegression():
    def __init__(self, X, y, iteration):
        self.m = rg.random((1,))
        self.b = rg.random((1, ))
        self.X = X
        self.y = y
        self.predicted_y = None
        self.error = None
        self.loss = None
        self.lr = 0.01
        self.iteration = iteration

    def forward(self):
        self.predicted_y = self.X * self.m + self.b
        self.error = self.y - self.predicted_y
        self.loss = np.mean(self.error**2)
        return self.loss
        

    def backward(self):
        grad_x = np.mean(-2 * self.error * self.X )
        grad_b = np.mean(-2 * self.error)
        self.m =  self.m - self.lr * grad_x
        self.b = self.b - self.lr * grad_b
        

    def train(self):

        for x in range(self.iteration):
            Loss = self.forward()
            print(f"Iteration: {x}, Loss: {Loss} ")
            self.backward()

        print(f"Loss: {self.loss}")
        print(f"Final weights: m: {self.m}, b: {self.b}")
       

In [63]:
data = [(1, 2), (3, 4), (5, 9), (2, 3)]
data = np.array(data)


In [64]:
X = data[:, 0]
y = data[:, 1]
print(X, y)

[1 3 5 2] [2 4 9 3]


In [65]:
Lr1 = LinearRegression(X, y, 100)

In [66]:
Lr1.train()

Iteration: 0, Loss: 5.190916729288378 
Iteration: 1, Loss: 4.913405179849822 
Iteration: 2, Loss: 4.72786734039233 
Iteration: 3, Loss: 4.599712135547791 
Iteration: 4, Loss: 4.507396840985461 
Iteration: 5, Loss: 4.4375046982337505 
Iteration: 6, Loss: 4.381679462271158 
Iteration: 7, Loss: 4.334716367949904 
Iteration: 8, Loss: 4.293373264935742 
Iteration: 9, Loss: 4.255630243002011 
Iteration: 10, Loss: 4.220228558061535 
Iteration: 11, Loss: 4.186383494831751 
Iteration: 12, Loss: 4.153605549845397 
Iteration: 13, Loss: 4.121589071770563 
Iteration: 14, Loss: 4.090142911277451 
Iteration: 15, Loss: 4.059147232666369 
Iteration: 16, Loss: 4.028526617929556 
Iteration: 17, Loss: 3.998233317049011 
Iteration: 18, Loss: 3.968236816939489 
Iteration: 19, Loss: 3.938517345375674 
Iteration: 20, Loss: 3.909061825460773 
Iteration: 21, Loss: 3.879861356188603 
Iteration: 22, Loss: 3.850909643392344 
Iteration: 23, Loss: 3.8222020225541167 
Iteration: 24, Loss: 3.7937348502008055 
Iteratio

In [67]:
Lr1.error

array([-1.42927444, -1.32899599,  1.77128245, -1.37913522])