# **Numpy from Scratch Beginners Guide**

#### **TABLE OF CONTENTS**
**1. Array and types of array in numpy** \
**2. How to create array in numpy?**

<br>

## **1. Array and types of array in numpy**

**Array** is a datatype in numpy which is similar to python's list but uses c directly for contiguous memory storation and is incredibly fast compared to standard list in python. Its very effective for large-scale numerical operations. 

Its features are:
- **Homogeneous**: Array in numpy is homogeneous and fixed-type. That means all the data are of same type(e.g. int64, float64, complex128). 
- **Multi-Dimensional**: Array in numpy is also called **ndarray**, and is the fundamental data structure. It can store data in any number of dimensions (1D, 2D, 3D, or more), making it highly flexible for scientific computing and data analysis.
- **Vectorized-Operations**: Array in numpy supports vectorization, where we can perform element-wise operations (like a+b) at near C-speeds which uses optimized, compiled code, eliminating the need for slow python loops.
- **Broadcasting**: Enables operations between arrays of different shapes in a flexible and efficient way.


### **Types of array**

#### **1. By number of dimensions**


**Nested array**: Arrays that have arrays as their elements
**Dimension**: Dimension in arrays is one level of array depth.

**0-D array**:
- e.g. 2, 45
- also known as scalars

**1-D array**:
- [1, 2, 3, 4, 5]
- uni-dimensional array
- has 0-D array as its elements.

**2-D array**:
- [[1, 2, 3], [2, 5, 7]]
- also called matrix/table.
- has 1-D array as its elements

**3-D array**:
- [ [[1, 2, 3], [2, 5, 7]], [[1, 2, 5], [3, 5, 9]] ]
- has 2-D array as its elements
- (2, 2, 3)

**N-D array**:
- It could be of any dimension
- Also called General Tensor


##### **Tensor**
Tensor is an mathematical object that generalizes scalars, vectors and matrices to higher dimensions. At its core, tensor is an n-dimensional array of numerical values. Tensor originated from physics where it meant objects that encode multi-directional relationship and transforms predictably under changes. 

In AI/ML, tensor is primarily seen as a multi-dimensional array used to store and manipulate data.

| Object   | Tensor order (rank) |
| -------- | ------------------- |
| Scalar   | 0-tensor            |
| Vector   | 1-tensor            |
| Matrix   | 2-tensor            |
| 3D array | 3-tensor            |
| ND array | N-tensor            |





## **2. How to create array in Numpy?**

The array object in Numpy is called `ndarray`. 
We can create `ndarray` using the `array`. <br>

*Note*: We can either pass a list or tuple. Since a set uses hashmap and is inherently unordered, Numpy can't guarantee the dtype or ordering.


In [17]:
import numpy as np

arr1 = np.array((1, 2, 3, 4))
arr2 = np.array([1, 2, 3, 4])

print(arr1)
print(arr2)

print(type(arr1))
print(type(arr2))


[1 2 3 4]
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### Checking the dimension of array using `ndim` attribute of array.

In [2]:
a = np.array(42)
b = np.array([2, 3, 5, 6, 8])
c = np.array([[8, 9, 10], [2, 6, 9]])

d = np.array([ [[2, 5, 6], [5, 6, 7 ]], [[3, 5, 2], [4, 2, 7]]])

In [3]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### While creating array, we can use `ndmin` to have the array in specific dimension.

In [21]:
a = np.array([1, 2, 3, 4, 5], ndmin=4)

In [23]:
print(a)

print(a.ndim)

[[[[1 2 3 4 5]]]]
4


In [15]:
import numpy as np

class Linear:
    def __init__(self, input_dim, output_dim):
        # Initialize weights randomly and biases to zero
        # We divide by sqrt(input_dim) to keep starting variance small (Xavier/He initialization)
        self.W = np.random.randn(input_dim, output_dim) / np.sqrt(input_dim)
        self.b = np.zeros(output_dim)

        # We will store X here during the forward pass so we can use it in the backward pass
        self.X_cache = None

        # Gradients will be stored here
        self.dW = None
        self.db = None

    def forward(self, X):
        """
        X shape: (batch_size, input_dim)
        Returns: Z shape (batch_size, output_dim)
        """
        # Save X for the backward pass
        self.X_cache = X

        # TODO: Calculate Z = XW + b
        Z = X @ self.W + self.b

        return Z

    def backward(self, dZ):
        """
        dZ shape: (batch_size, output_dim)
        Returns: dX shape (batch_size, input_dim)
        """
        X = self.X_cache

        # TODO: Calculate dW, db, and dX based on the formulas above
        self.dW = X.T @ dZ
        self.db = np.sum(dZ, axis=0)
        dX = dZ @ self.W.T

        return dX

In [17]:
# stable_softmax()

def naive_softmax(X):
  exps = np.exp(X)
  return exps/np.sum(exps, axis=-1, keepdims=True)




In [18]:
naive_softmax([1000, 1001, 1002])

/tmp/ipython-input-164/1824532343.py:4: RuntimeWarning: overflow encountered in exp
  exps = np.exp(X)
/tmp/ipython-input-164/1824532343.py:5: RuntimeWarning: invalid value encountered in divide
  return exps/np.sum(exps, axis=-1, keepdims=True)


array([nan, nan, nan])

In [23]:
def stable_softmax(X):
  exps = np.exp(X - np.max(X, axis=-1, keepdims=True))
  return exps/np.sum(exps, axis=-1, keepdims=True)

In [24]:
stable_softmax([1000, 1001, 1002])

array([0.09003057, 0.24472847, 0.66524096])