### Prerequisites
1. Linear function
2. Gradient calculation
3. Parameters update

In [ ]:
import numpy as np
rg = np.random.default_rng()

rg.random((3,))

array([0.29804961, 0.34339067, 0.66891588])

In [9]:

class LinearRegression():
    def __init__(self, X, y, iteration):
        self.m = rg.random((1,))
        self.b = rg.random((1, ))
        self.X = X
        self.y = y
        self.predicted_y = None
        self.error = None
        self.loss = None
        self.lr = 0.01
        self.iteration = iteration

    def forward(self):
        self.predicted_y = self.X * self.m + self.b
        self.error = self.y - self.predicted_y
        self.loss = np.mean(self.error**2)
        return self.loss
        
    def backward(self):
        grad_x = np.mean(-2 * self.error * self.X )
        grad_b = np.mean(-2 * self.error)
        self.m =  self.m - self.lr * grad_x
        self.b = self.b - self.lr * grad_b
    
    def train(self):

        for x in range(self.iteration):
            Loss = self.forward()
            print(f"Iteration: {x}, Loss: {Loss} ")
            self.backward()

        print(f"Loss: {self.loss}")
        print(f"Final weights: m: {self.m}, b: {self.b}")
       

In [10]:
data = [(1, 2), (3, 4), (5, 9), (2, 3)]
data = np.array(data)


In [11]:
X = data[:, 0]
y = data[:, 1]
print(X, y)

[1 3 5 2] [2 4 9 3]


In [12]:
Lr1 = LinearRegression(X, y, 100)

In [13]:
Lr1.train()

Iteration: 0, Loss: 10.019092037132257 
Iteration: 1, Loss: 6.430193104708083 
Iteration: 2, Loss: 4.194804793900907 
Iteration: 3, Loss: 2.802328493102739 
Iteration: 4, Loss: 1.9347850553599166 
Iteration: 5, Loss: 1.394150552602313 
Iteration: 6, Loss: 1.0571040706963464 
Iteration: 7, Loss: 0.8468465588544691 
Iteration: 8, Loss: 0.7155508063917899 
Iteration: 9, Loss: 0.6334320339046668 
Iteration: 10, Loss: 0.5819415218180898 
Iteration: 11, Loss: 0.5495278914288794 
Iteration: 12, Loss: 0.5289974108302131 
Iteration: 13, Loss: 0.5158701055937042 
Iteration: 14, Loss: 0.507356014345277 
Iteration: 15, Loss: 0.5017176442325011 
Iteration: 16, Loss: 0.49787293527569476 
Iteration: 17, Loss: 0.4951480034332184 
Iteration: 18, Loss: 0.4931231594862778 
Iteration: 19, Loss: 0.4915370161410678 
Iteration: 20, Loss: 0.4902267700046561 
Iteration: 21, Loss: 0.48909101173528474 
Iteration: 22, Loss: 0.488066565782541 
Iteration: 23, Loss: 0.48711406716001415 
Iteration: 24, Loss: 0.486208

In [14]:
Lr1.error

array([ 0.25172392, -1.00912857,  0.73001893, -0.37870233])

### **Vectorized Implementation** 

In [15]:
class LinearRegression():
    def __init__(self, lr=0.01, iterations=1000):
        self.lr = lr
        self.iterations = iterations
        self.W = None
        self.b = None
        self.loss_history = []

    def _param_init(self, n_features):
          
        self.W = np.random.randn(n_features, 1) * 0.01
        self.b = 0.0


    def forward(self, X):

        predicted_y = X @ self.W + self.b
        return predicted_y
    
    def backward(self, X, y, predicted_y):

        n_samples = X.shape[0]

        error = predicted_y - y

        grad_W = (2 / n_samples) * X.T @ error
        grad_b = (2 / n_samples) * np.sum(error)

        self.W -= self.lr * grad_W
        self.b -= self.lr * grad_b



    def fit(self, X, y):

        if y.ndim == 1:
            y = y.reshpae(-1, 1)

        n_samples, n_features = X.shape
        self._param_init(n_features)

        for i in range(self.iterations):
            predicted_y = self.forward(X)

            loss = np.mean((predicted_y - y)**2)
            self.loss_history.append(loss)

            self.backward(X, y, predicted_y)

            if i % (self.iterations // 10) == 0 or i == self.iterations - 1:
                print(f"Iteration: {i:4d} | Loss: {loss:.4f}")

    def predict(self, X):
        return self.forward(X)




In [16]:
if __name__ == "__main__":
    # 1. Create some dummy data (100 houses, 3 features each)
    np.random.seed(42)
    X_train = np.random.rand(100, 3)
    
    # 2. Define the "True" rules of the universe that the model needs to learn
    # True weights: [3.0, 1.5, -2.0], True bias: 5.0
    true_W = np.array([[3.0], [1.5], [-2.0]])
    
    # Generate targets (y) based on the true weights, plus a tiny bit of random noise
    y_train = X_train @ true_W + 5.0 + (np.random.randn(100, 1) * 0.1) 
    
    # 3. Initialize our custom model
    print("Starting Training...")
    model = LinearRegression(lr=0.1, iterations=500)
    
    # 4. Train the model
    model.fit(X_train, y_train)
    
    # 5. Check the results (They should be very close to [3.0, 1.5, -2.0] and 5.0)
    print("\n--- Training Complete ---")
    print("True Weights:      [ 3.0,  1.5, -2.0]")
    print("Learned Weights:\n", np.round(model.W.flatten(), 2))
    print(f"True Bias:         5.0")
    print(f"Learned Bias:      {model.b:.2f}")

Starting Training...
Iteration:    0 | Loss: 39.9997
Iteration:   50 | Loss: 0.2965
Iteration:  100 | Loss: 0.0814
Iteration:  150 | Loss: 0.0310
Iteration:  200 | Loss: 0.0167
Iteration:  250 | Loss: 0.0120
Iteration:  300 | Loss: 0.0103
Iteration:  350 | Loss: 0.0096
Iteration:  400 | Loss: 0.0094
Iteration:  450 | Loss: 0.0093
Iteration:  499 | Loss: 0.0092

--- Training Complete ---
True Weights:      [ 3.0,  1.5, -2.0]
Learned Weights:
 [ 3.04  1.49 -1.93]
True Bias:         5.0
Learned Bias:      4.96
