In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])

In [3]:
np.ndim(arr2)

2

In [4]:
new_arr1 = np.array(arr1, ndmin=4)
new_arr1

array([[[[1, 2, 3, 4]]]])

In [5]:
new_arr1.ndim

4

In [6]:
new_arr1

array([[[[1, 2, 3, 4]]]])

In [7]:
new_arr1.dtype.name

'int32'

### **Using zeros to create arrays**

In [8]:
zero_arrs = np.zeros((3, 4))
zero_arrs

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **Using ones to create arrays**

In [9]:
one_arrs = np.ones((3, 4), dtype=float)
one_arrs 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
one_arrs.itemsize

8

In [11]:
one_arrs.strides

(32, 8)

#### **strides**:   number of bytes to jump to get to the next element.
| Element | Address |
| ------- | ------- |
| 10      | 1000    |
| 20      | 1004    |
| 30      | 1008    |


##### **(32, 8)**: 32 bytes to jump to next row and 8 bytes to next elements. 

### **Using empty to create arrays**

In [12]:
arrs = np.empty((3, 5))
arrs

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### **Using arrange to create arrays**

In [18]:
# arange creates arras with steps and are sequentials

arrs = np.arange(3, 100, 10) 
arrs 

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

### **Using linspace to create arrays**

In [19]:
arrs = np.linspace(3, 100, 10)
arrs

array([  3.        ,  13.77777778,  24.55555556,  35.33333333,
        46.11111111,  56.88888889,  67.66666667,  78.44444444,
        89.22222222, 100.        ])

### **Basic operations**

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [23]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])

arr3 = arr1 + arr2
arr3

array([2, 4, 6, 8])

In [24]:
arr3**2

array([ 4, 16, 36, 64])

#### **Matrix Multiplications**

In [ ]:
arr1 = np.array([
    [1, 2],
    [2, 3]
])

arr2 = np.array([
    [2, 1],
    [8, 2]
])

# Product Operator
arr3 = arr1 * arr2 # Multiplation happens elementwise
# print(arr3)
# [[ 2  2]
#  [16  6]]


# Matrix Product

arr4 = arr1 @ arr2
print(arr4)
# [[18  5]
#  [28  8]]

# Another Product

arr5 = arr1.dot(arr2)
print(arr5)
# [[18  5]
#  [28  8]]


[[18  5]
 [28  8]]
[[18  5]
 [28  8]]
