In [1]:
import numpy as np

In [2]:
# Arraay creations
arr1 = np.array([[1, 2], [2, 1]])

print(arr1.shape)
print(arr1.size)
print(arr1.itemsize)
print(arr1.ndim)
print(arr1.strides)


(2, 2)
4
4
2
(8, 4)


In [3]:

arr2 = np.array(arr1, ndmin=4)
print(arr2)
print(arr2.shape)

[[[[1 2]
   [2 1]]]]
(1, 1, 2, 2)


In [4]:
arr3 = np.array([1, 2, 3, 4])
print(arr3.shape)

(4,)


In [5]:
# Creating with zeros
arr4 = np.zeros((3, 4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Creating with ones
arr5 = np.ones((3, 4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr6 = np.empty((3, 4))
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Creating array with arange
arr7 = np.arange(3, 100, 5)
arr7

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83,
       88, 93, 98])

In [9]:
# Creating array with linspace
arr8 = np.linspace(3, 100, 100)
arr8

array([  3.        ,   3.97979798,   4.95959596,   5.93939394,
         6.91919192,   7.8989899 ,   8.87878788,   9.85858586,
        10.83838384,  11.81818182,  12.7979798 ,  13.77777778,
        14.75757576,  15.73737374,  16.71717172,  17.6969697 ,
        18.67676768,  19.65656566,  20.63636364,  21.61616162,
        22.5959596 ,  23.57575758,  24.55555556,  25.53535354,
        26.51515152,  27.49494949,  28.47474747,  29.45454545,
        30.43434343,  31.41414141,  32.39393939,  33.37373737,
        34.35353535,  35.33333333,  36.31313131,  37.29292929,
        38.27272727,  39.25252525,  40.23232323,  41.21212121,
        42.19191919,  43.17171717,  44.15151515,  45.13131313,
        46.11111111,  47.09090909,  48.07070707,  49.05050505,
        50.03030303,  51.01010101,  51.98989899,  52.96969697,
        53.94949495,  54.92929293,  55.90909091,  56.88888889,
        57.86868687,  58.84848485,  59.82828283,  60.80808081,
        61.78787879,  62.76767677,  63.74747475,  64.72

In [10]:
# Operations

a = np.array([1, 2])
b = np.array([3, 4])

c = a + b
c

array([4, 6])

In [11]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [3, 4],
    [2, 1]
])

c = a + b
print(c)

d = a*b
print(d)

[[4 6]
 [5 5]]
[[3 8]
 [6 4]]


In [12]:
# matrix multiplication

b_a = np.array([
    [3],
    [4],
    [5]
])

# e = a @ b_a # error 

f = a @ b
f

array([[ 7,  6],
       [17, 16]])

In [13]:
g = a.dot(b)
g

array([[ 7,  6],
       [17, 16]])

In [17]:
arr = np.array([[2, 2], [1, 1], [2, 3]])
arr1 = np.array([2])

arr2 = arr * arr1
arr2



array([[4, 4],
       [2, 2],
       [4, 6]])