In [1]:
import numpy as np

In [2]:
def softmax(Z):

    return np.exp(Z) / np.sum(np.exp(Z), axis=0, keepdims=True)

In [3]:
def scaled_dot_product_attnetion(Q, K, V, mask=None):

    d_k = Q.shape[-1]
    scores = Q @ K.transpose(0, 2, 1)
    scaled_scores = scores / np.sqrt(d_k)

    if mask is not None:
        scaled_scores += mask

    weights = softmax(scaled_scores)
    output = weights @ V
    return output

In [4]:
def softmax(Z):

    return np.exp(Z)/ np.sum(np.exp(Z), axis=-1, keepdims=True)

In [6]:

def softmax(Z):
    Z = Z - np.max(Z, axis=-1, keepdims=True)
    return np.exp(Z)/ np.sum(np.exp(Z), axis=-1, keepdims=True)

def scaled_dot_product_attention(Q, K, V, mask=None):

    d_k = Q.shape[-1]
    seq_len = Q.shape[-2]
    scores = Q @ K.transpose(0, 2, 1)
    scaled_scores = scores / np.sqrt(d_k)

    if mask is not None:
        scaled_scores += mask
    weights = softmax(scaled_scores)
    output = weights @ V
    return output, weights 



In [7]:
rng = np.random.default_rng(42)
N, seq_len, d_k, d_v = 2, 4, 8, 8

Q = rng.standard_normal((N, seq_len, d_k))
K = rng.standard_normal((N, seq_len, d_k))
V = rng.standard_normal((N, seq_len, d_v))

# build causal mask
mask = np.triu(np.ones((seq_len, seq_len)), k=1)
mask[mask == 1] = -np.inf

output, weights = scaled_dot_product_attention(Q, K, V, mask)

print(output.shape)   # should be (2, 4, 8)
print(weights.shape)  # should be (2, 4, 4)
print(weights[0])     # each row should sum to 1.0
print(weights[0].sum(axis=-1))  # should be [1. 1. 1. 1.]

(2, 4, 8)
(2, 4, 4)
[[1.         0.         0.         0.        ]
 [0.32254365 0.67745635 0.         0.        ]
 [0.19032159 0.42211611 0.3875623  0.        ]
 [0.11063801 0.61304715 0.17824882 0.09806603]]
[1. 1. 1. 1.]


In [9]:
arr = np.array([[1, 2, 3], [2, 3, 4], [5, 6, 7]])

mask = np.triu(np.ones((3, 3)), k=1)

print(mask)

mask[mask==1] = -np.inf
mask[mask==0] = 0

mask



[[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]


array([[  0., -inf, -inf],
       [  0.,   0., -inf],
       [  0.,   0.,   0.]])

### **Softmax Instability**

In [1]:
import numpy as np

print(np.exp(700))
print(np.exp(710))
print(np.exp(1000))


1.0142320547350045e+304
inf
inf


C:\Users\dell\AppData\Local\Temp\ipykernel_5056\3800974056.py:4: RuntimeWarning: overflow encountered in exp
  print(np.exp(710))
C:\Users\dell\AppData\Local\Temp\ipykernel_5056\3800974056.py:5: RuntimeWarning: overflow encountered in exp
  print(np.exp(1000))


float64 max ≈ 1.8 × 10³⁰⁸

In [3]:

# unstable
z = np.array([1000.0, 1001.0, 1002.0])
print(np.exp(z))
print(np.exp(z) / np.sum(np.exp(z)) )

C:\Users\dell\AppData\Local\Temp\ipykernel_5056\1170416457.py:3: RuntimeWarning: overflow encountered in exp
  print(np.exp(z))


[inf inf inf]
[nan nan nan]


C:\Users\dell\AppData\Local\Temp\ipykernel_5056\1170416457.py:4: RuntimeWarning: overflow encountered in exp
  print(np.exp(z) / np.sum(np.exp(z)) )
C:\Users\dell\AppData\Local\Temp\ipykernel_5056\1170416457.py:4: RuntimeWarning: invalid value encountered in divide
  print(np.exp(z) / np.sum(np.exp(z)) )


In [4]:
z = z - np.max(z)
print(z)

[-2. -1.  0.]


In [5]:
print(np.exp(z))
print(np.exp(z) / np.sum(np.exp(z)))

[0.13533528 0.36787944 1.        ]
[0.09003057 0.24472847 0.66524096]
